name: chat_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter:
    sdk: flutter
  firebase_core: ^2.13.0
  firebase_core_desktop: ^1.0.2
  animated_text_kit: ^4.2.2
  firebase_auth: ^4.6.1
  cloud_firestore: ^4.7.1
  intl: ^0.18.1
dev_dependencies:
  flutter_lints: 2.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
